name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set BRANCH_TAG
        uses: nimblehq/branch-tag-action@v1.2
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Set HEROKU_APP_NAME
        run: echo "HEROKU_APP_NAME=nimble-link" >> $GITHUB_ENV

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: $HEROKU_APP_NAME
          heroku_email: ${{ secrets.HEROKU_ACCOUNT_EMAIL }}
          usedocker: true
